package com.indiepass.sdk;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


import java.util.concurrent.CompletableFuture;

public class IndiePassSDK {

    public static void load() {
        try {
            System.loadLibrary("indiepasslib");
        } catch (UnsatisfiedLinkError e) {
            System.err.println("Native code library failed to load. " + e);
            System.exit(1);
        }
    }

    public static CompletableFuture<Boolean> unlockAchievement(String achievement) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return IndiePassSDKJNI.unlockAchievement(achievement);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }

    public static CompletableFuture<Boolean> lockAchievement(String achievement) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return IndiePassSDKJNI.lockAchievement(achievement);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }

    public static void setSimul(boolean isSimul) {
        IndiePassSDKJNI.setSimul(isSimul);
    }

    public static CompletableFuture<Boolean> verifyCertificate(int idGame, String publicKey) {
        return CompletableFuture.supplyAsync(() -> {
            try {
                return IndiePassSDKJNI.verifyCertificate(idGame, publicKey);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });
    }

}
