package com.indiepass.sdk;/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class IndiePassSDKJNI {
  public final static native boolean unlockAchievement(String jarg1);
  public final static native boolean lockAchievement(String jarg1);
  public final static native void setSimul(boolean jarg1);
  public final static native boolean verifyCertificate(int jarg1, String jarg2);
}
